//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WisconsinTest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Psychologists
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Psychologists()
        {
            this.Patients = new HashSet<Patients>();
        }
    
        public int PsychologistId { get; set; }
        public int UserId { get; set; }
        [Required(ErrorMessage = "Nalezy podac imie.")]
        [Display(Name = "Imie")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Nalezy podac nazwisko.")]
        [Display(Name = "Nazwisko")]
        public string Surname { get; set; }
        [Required(ErrorMessage = "Nalezy podac numer telefonu.")]
        [Display(Name = "Numer telefonu")]
        public string PhoneNumber { get; set; }
        [Required(ErrorMessage = "Nalezy podac adres.")]
        [Display(Name = "Adres")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Nalezy podac date urodzenia.")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "(0:DD/mm/yyyy)")]
        [Display(Name = "Data urodzenia")]
        public System.DateTime BirthDate { get; set; }
        [Required(ErrorMessage = "Nalezy podac PESEL.")]
        [Display(Name = "PESEL")]
        public string PESEL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patients> Patients { get; set; }
        public virtual Users Users { get; set; }
    }
}
